version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${VITE_BACKEND_URL:-http://localhost:3000}
    ports:
      - "80:80"
    environment:
      - API_URL=${VITE_BACKEND_URL:-http://localhost:3000}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:3000}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
