name: CI

on:
  pull_request:
    branches:
      - "!main"
      - "*"

concurrency:
  group: CI-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  udeps:
    name: Check unused dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
      - name: Install depcheck
        run: npm install -g depcheck
      - name: Check for unused dependencies
        run: depcheck --ignore-dirs=dist,coverage,build,public,docs --ignores=@storybook/*,@testing-library/*,oxlint,storybook,vite-plugin-oxlint,postcsstypescript,tailwindcss,@/*,@vitest/coverage-v8,prettier

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
      - name: Pnpm Install
        run: pnpm install --frozen-lockfile
      - name: Run Vitest with coverage
        run: pnpm vitest run --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
      - name: Pnpm Install
        run: pnpm install --frozen-lockfile
      - name: Run prettier
        run: pnpm prettier --check .

  oxlint:
    name: Lint JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run oxlint
        run: npx --yes oxlint@0.11.1 -c .oxlintrc.json --ignore-path=.oxlintignore --import-plugin --jsdoc-plugin --deny-warnings
